package net.bohush.english;

public class Data {
	static private String[] data = {
			"Introductions\n"
			 + "John:	Hi, Teresa.\n"
			 + "Teresa:	Good morning John. How are you?\n"
			 + "John:	I'm fine thanks. And you?\n"
			 + "Teresa:	Not bad. John, this is Andres, our new colleague.\n"
			 + "John:	Oh hi! Pleased to meet you!\n"
			 + "Andres:	Nice to meet you, too.\n"
			 + "Teresa:	Andres is the new maintenance supervisor.\n"
			 + "John:	I see. Welcome aboard. Where are you from?\n"
			 + "Andres:	I'm from Mexico.\n"
			 + "John:	Really?\n"
			 + "Andres:	Yes. I'm from Mexico City.\n"
			 + "John:	That's an interesting city.\n"
			 + "John:	Well, it's nice meeting you, Andres. See you later.\n"
			 + "Teresa:	Bye.\n"
			 + "Andres:	Bye.\n",

			"Family relationship\n"
			 + "Peter:	Hello!\n"
			 + "Linda:	Hi Peter, come on in.\n"
			 + "Peter:	Thanks. Where's everyone else?\n"
			 + "Linda:	My sister and her husband are in the kitchen.\n"
			 + "Linda:	Two or three other people are in the kitchen, too.\n"
			 + "Peter:	This is a very nice apartment.\n"
			 + "Linda:	Thanks. My parents own it.\n"
			 + "Peter:	I see. Is this a picture of your parents over here?\n"
			 + "Linda:	Yes, this is my entire family.\n"
			 + "Peter:	Who's who?\n"
			 + "Linda:	Well, these are my parents, Linda and Joseph.\n"
			 + "Peter:	And who's this?\n"
			 + "Linda:	This is my brother Thomas.\n"
			 + "Linda:	I also have a sister but she's not in the picture. She's here tonight.\n"
			 + "Peter:	And who's the little girl?\n"
			 + "Linda:	Well, that's me, of course.\n"
			 + "Peter:	Really? You still have the same beautiful smile!\n"
			 + "Linda:	What a sweet thing to say!\n"
			 + "Peter:	Well, that's the kind of guy I am.\n",

			"Asking for information\n"
			 + "Chin:	Mom, where are my blue pants?\n"
			 + "Mother:	Check in your room.\n"
			 + "Chin:	No, they're not there.\n"
			 + "Mother:	Then look on the ironing board.\n"
			 + "Chin:	OK. Here they are! Mom!\n"
			 + "Mother:	Yes, Chin, what is it now?\n"
			 + "Chin:	Sorry, but I can't find my sneakers.\n"
			 + "Mother:	I'm sure you know where they are. Just think for a minute.\n"
			 + "Chin:	Oh! Now I see them. I guess you're right.\n"
			 + "Mother:	Of course I am. I'm your mother.\n"
			 + "Chin:	Well, then tell me where my car keys are.\n"
			 + "Mother:	How about in your coat pocket?\n"
			 + "Chin:	No!\n"
			 + "Mother:	Maybe they're in your gym bag.\n"
			 + "Chin:	Great! They're here. Thanks, Mom. See you later!\n"
			 + "Mother:	Bye! Someday he's going to lose his head!\n",

			"Clothing, colors and size\n"
			 + "Sharon:	Oh I love the clothes in this store, but they cost way too much.\n"
			 + "Pat:	I know but I need a dress for Robin and Mike's wedding.\n"
			 + "Pat:	What do you think of this one?\n"
			 + "Sharon:	Now, that is gorgeous, and you look great in blue.\n"
			 + "Pat:	But I like this red one, too.\n"
			 + "Sharon:	Well, try both of them on.\n"
			 + "Pat:	Is there a size ten in blue?\n"
			 + "Sharon:	Yes, right here.\n"
			 + "Sharon:	The fitting rooms are around the corner, by the children's department.\n"
			 + "Sharon:	I like the blue.\n"
			 + "Pat:	And it's comfortable too. Is it too short, though?\n"
			 + "Sharon:	No. You look beautiful, really.\n"
			 + "Pat:	Thanks. Excuse me, how much is this dress?\n"
			 + "Clerk:	You're lucky. All women's fashions are on sale today.\n"
			 + "Clerk:	Let's see... this dress is twenty five percent off.\n"
			 + "Pat:	I'm convinced. I even have shoes to match.\n"
			 + "Sharon:	That's reason enough right there.\n",

			"The weather, seasons, months and days\n"
			 + "Jim:	I need some hot coffee. I'm so cold!\n"
			 + "An:	I know. I think my feet are frozen.\n"
			 + "Waitress:	Are you ready to order?\n"
			 + "Jim:	Yes, some coffee, please.\n"
			 + "An:	Tea with lemon for me, please.\n"
			 + "Waitress:	Cream and sugar with your coffee, sir?\n"
			 + "Jim:	Yes, please.\n"
			 + "Waitress:	Just a minute.\n"
			 + "Jim:	What's the weather forecast for today?\n"
			 + "An:	Chance of snow and temperatures in the teens until Tuesday.\n"
			 + "An:	Oh, no! How can you stand Boston winters?\n"
			 + "Jim:	Good question. I bet you miss Vietnam. What's the weather like there now?\n"
			 + "An:	Around seventy degrees. It's warm in January, but it rains a lot.\n"
			 + "Jim:	Well, I prefer rain to snow and ice.\n"
			 + "Waitress:	Here's your coffee and tea. I hope it warms you up!  \n",

			"Time\n"
			 + "Antonio:	Well, finally.\n"
			 + "Jean:	Hi, I'm sorry I'm late.\n"
			 + "Antonio:	You were supposed to be here at seven. Where were you? I was worried.\n"
			 + "Jean:	I'm sorry, but the bus was twenty minutes late.\n"
			 + "Antonio:	I understand, but now we're late for the seven-fifteen show.\n"
			 + "Jean:	Sorry!\n"
			 + "Antonio:	That's OK. The next show starts at nine-thirty.\n"
			 + "Jean:	What time is it now?\n"
			 + "Antonio:	No watch! No wonder you're always late! It's twenty to eight.\n"
			 + "Jean:	Well, we have almost two hours to kill.\n"
			 + "Jean:	How about dinner before the movie? Are you hungry?\n"
			 + "Antonio:	Now that you mention it, yes.\n"
			 + "Jean:	How about pizza?\n"
			 + "Antonio:	I'd rather have Mexican food.\n"
			 + "Jean:	Fine, my treat.\n"
			 + "Antonio:	I like that. You can be late more often.\n",

			"Daily activities\n"
			 + "Diana:	Steven, good morning.\n"
			 + "Steven:	Diana! What a surprise!\n"
			 + "Diana:	Do you jog here every morning?\n"
			 + "Steven:	Yes. Well, I try to, anyway. How about you?\n"
			 + "Diana:	I jog every day, but I don't always come here.\n"
			 + "Steven:	Where do you usually go?\n"
			 + "Diana:	I go to Central Park pretty often.\n"
			 + "Steven:	Wow, that's quite far. What time do you get up?\n"
			 + "Diana:	Usually between six and six-fifteen.\n"
			 + "Steven:	That's awfully early for me!\n"
			 + "Diana:	You're not an early riser, are you?\n"
			 + "Steven:	Not exactly. But you obviously are.\n"
			 + "Diana:	Well, to me it's worth it to go jogging in Central Park. It's so peaceful.\n"
			 + "Steven:	So, would you like to join me for a cup of coffee?\n"
			 + "Steven:	I know this cozy little coffee shop on the corner of Bleecker and MacDougal.\n"
			 + "Diana:	That sounds nice.\n"
			 + "Steven:	Great! See you there in thirty minutes? \n"
			 + "Diana:	OK! See you there!\n",

			"Ongoing activities\n"
			 + "Camille:	Fabiola, Rick... What are you guys doing here?\n"
			 + "Fabiola:	Camille, what a surprise!\n"
			 + "Rick:	Hi. We're going to the mall. How about you?\n"
			 + "Camille:	I'm going to the hardware store.\n"
			 + "Camille:	I need to buy some paint, rollers, and brushes.\n"
			 + "Fabiola:	Why is that?\n"
			 + "Camille:	Well, because I'm renovating my kitchen and my bathroom.\n"
			 + "Rick:	How is it coming along?\n"
			 + "Camille:	So far so good. I'm painting the kitchen tonight.\n"
			 + "Rick:	Is your husband helping you?\n"
			 + "Camille:	Oh, yeah, he likes to work around the house.\n"
			 + "Fabiola:	That's great.\n"
			 + "Fabiola:	Listen, do you want to help us paint our kitchen and bathroom?\n"
			 + "Camille:	I don't think so. But you are welcome to borrow our equipment.\n"
			 + "Rick:	Thanks, but I can't imagine Fabiola painting the walls.\n"
			 + "Fabiola:	Look who's talking.\n"
			 + "Fabiola:	You're not so crazy about do-it-yourself projects, either.\n"
			 + "Rick:	Yes, I am. I'm just too busy.\n"
			 + "Fabiola:	Oh, sure.\n",

			"Sports\n"
			 + "Jose:	Hey Dave, can you take me to the train station?\n"
			 + "David:	Sure, but I have practice in thirty minutes.\n"
			 + "Jose:	I'm ready. Let's go. So, how is practice going?\n"
			 + "David:	Well, it's tough.\n"
			 + "David:	We have to build endurance to run with the ball, tackle and take hits.\n"
			 + "Jose:	But isn't the most important thing to kick the ball?\n"
			 + "David:	We may be talking about two different sports.\n"
			 + "David:	I play what we call 'football' here in the United States, not soccer.\n"
			 + "Jose:	Oh!\n"
			 + "David:	We don't kick the ball very much. We have to carry it with our hands.\n"
			 + "Jose:	I see.\n"
			 + "David:	How about you? Are you playing any sports?\n"
			 + "Jose:	I might try baseball next semester, but I don't know how to play.\n"
			 + "David:	There's nothing you can't learn.\n"
			 + "Jose:	I hope you're right. Oh, here we are. Thank you!\n"
			 + "David:	You're welcome!\n",

			"Likes and dislikes\n"
			 + "Sean:	This seems like a nice place.\n"
			 + "Carol:	I hope the food is good.\n"
			 + "Waitress:	Good evening! How are you tonight?\n"
			 + "Sean:	Fine, thanks. \n"
			 + "Waitress:	Our specials tonight are a beef casserole with mushrooms for ten ninety-five\n"
			 + "	and a fresh salmon in garlic sauce for twelve ninety-five.\n"
			 + "Waitress:	Would you like something to drink first?\n"
			 + "Sean:	Yes, please. We'd like a bottle of dry white wine.\n"
			 + "Waitress:	Is a Chardonnay OK?\n"
			 + "Sean:	Yes, that sounds good.\n"
			 + "Waitress:	Do you need a minute to look at the menus?\n"
			 + "Sean:	Yes, please.\n"
			 + "Waitress:	OK. I'll be right back with your wine.\n"
			 + "Sean:	Do you know what you want?\n"
			 + "Carol:	No, I'm not quite sure yet. What about you?\n"
			 + "Sean:	The fish special sounds great.\n"
			 + "Waitress:	Here is your wine. What can I get you to eat?\n"
			 + "Sean:	I'd like the salmon special.\n"
			 + "Waitress:	And you, ma'am?\n"
			 + "Carol:	I'd like the grilled chicken breast and a large spinach salad to start.\n"
			 + "Waitress:	Good choice. The chicken is delicious! Anything else?\n"
			 + "Carol:	Not at the moment, thanks.\n",

			"Health\n"
			 + "Patient:	Hi, this is Carlo Pirelli calling. I need to see the doctor immediately.\n"
			 + "Receptionist:	Is this an emergency?\n"
			 + "Patient:	Yes, I have a terrible stomachache and a fever.\n"
			 + "Receptionist:	Is this your first time in this office? \n"
			 + "Patient:	No, I'm a regular patient.\n"
			 + "Receptionist:	Go ahead and come in right away.\n"
			 + "Patient:	Hi, my name is Carlo Pirelli.\n"
			 + "Receptionist:	Yes. Take a seat right here for a moment.\n"
			 + "Nurse:	Hello. Let me take your temperature and blood pressure.\n"
			 + "Patient:	Sure.\n"
			 + "Nurse:	Well, your temperature is a little high, but your blood pressure is perfect for your age.\n"
			 + "Patient:	That's good to hear.\n"
			 + "Nurse:	The doctor will be right in.\n"
			 + "Patient:	Thanks.\n"
			 + "Doctor:	Mister Pirelli, I hear you're in pain.\n"
			 + "Patient:	Yes. I have a stomachache and I feel a little dizzy.\n"
			 + "Doctor:	Does it hurt if I press here?\n"
			 + "Patient:	Yes.\n"
			 + "Doctor:	Take a deep breath. It doesn't seem to be anything serious. You probably just have the flu. There's a virus going around. Don't worry about it.\n"
			 + "Patient:	So, there's nothing I can do?\n"
			 + "Doctor:	Go home, rest and drink lots of fluids. If you don't feel better in a couple of days, come back to see me.\n"
			 + "Patient:	Thanks.\n",

			"Banking\n"
			 + "Clerk:	How can I help you today?\n"
			 + "Mario:	We need to open a checking account.\n"
			 + "Clerk:	Well, there are two options. First, our standard checking account has no minimum balance requirement, but there's a monthly service fee of ten dollars.\n"
			 + "Laura:	What about the other option? \n"
			 + "Clerk:	Our golden checking account has a minimum balance requirement of one thousand dollars, but there's no monthly service fee. Money orders and traveler's checks are free as well.\n"
			 + "Mario:	Which choice would you prefer?\n"
			 + "Laura:	A ten dollar service fee is a lot of money, but I think we should take the standard checking account anyway.\n"
			 + "Mario:	I agree.\n"
			 + "Clerk:	Do you want this to be a joint account?\n"
			 + "Laura:	Yes, please.\n"
			 + "Clerk:	Please fill out these forms. Also, I need two forms of identification.\n"
			 + "Mario:	Whose name will appear on the checks?\n"
			 + "Clerk:	Both of your names.\n"
			 + "Laura:	Can we get two ATM cards with this account?\n"
			 + "Clerk:	Certainly.\n",

			"Shopping for food\n"
			 + "Tom:	How about chicken for dinner tonight?\n"
			 + "Kathy:	Sounds good. Do you have the shopping list?\n"
			 + "Tom:	No, I don't. \n"
			 + "Kathy:	I don't either. It's probably at home on the kitchen counter. \n"
			 + "Tom:	Great! Do you have any idea what we need? \n"
			 + "Kathy:	Well, the chicken and something to serve on the side.\n"
			 + "Tom:	How about vegetables and rice?\n"
			 + "Kathy:	Fine. I'll get some carrots and a package of rice.\n"
			 + "Tom:	I think we're out of milk. I'll get some.\n"
			 + "Kathy:	Oh. And let's get some eggs for tomorrow morning.\n"
			 + "Tom:	You're not supposed to eat so many eggs. It's not good for you.\n"
			 + "Kathy:	Look who's talking. With your usual diet of meat and potatoes, you're a real health nut.\n"
			 + "Cashier:	Your total is twenty three eighty three.\n"
			 + "Kathy:	Here you go.\n"
			 + "Cashier:	Out of thirty. Six dollars and seventeen cents is your change.\n"
			 + "Tom:	Oh, no!\n"
			 + "Kathy:	What?\n"
			 + "Tom:	The chicken!\n",

			"Looking for an apartment\n"
			 + "Lady:	Hello?\n"
			 + "Mark:	Hi! Is the apartment you advertised in the paper still available?\n"
			 + "Lady:	Yes. \n"
			 + "Mark:	May I ask a few questions? \n"
			 + "Lady:	Certainly. \n"
			 + "Mark:	How big is the apartment?\n"
			 + "Lady:	It has one bedroom, a living area, a kitchen, and a small den. The den used to be a separate bedroom, but the former tenant decided to tear the wall down.\n"
			 + "Mark:	Does it get any light?\n"
			 + "Lady:	Oh, yes. The apartment faces south.\n"
			 + "Mark:	How much is the rent?\n"
			 + "Lady:	Nine fifty a month plus one month's rent as a security deposit.\n"
			 + "Mark:	One last question. Why did the last tenant leave?\n"
			 + "Lady:	His company offered him a job in New York. He moved to the east coast last month.\n"
			 + "Mark:	That's where I'm from. I just moved here a week ago.\n"
			 + "Lady:	What a coincidence!\n"
			 + "Mark:	Yes. Can I see the apartment?\n"
			 + "Lady:	Sure. How about tomorrow at four thirty?\n"
			 + "Mark:	That sounds great. See you then.\n",

			"Moving to another city\n"
			 + "Ana:	Excuse me. Can I interrupt you?\n"
			 + "Jim:	Sure, what can I do for you?\n"
			 + "Ana:	I'm Ana, the new tenant in apartment six F. \n"
			 + "Jim:	Oh right. Someone told me that we had a new neighbor. I'm Jim. \n"
			 + "Ana:	Nice to meet you. I'm still somewhat unfamiliar with this area. I need to get to a pharmacy quickly. Is there one nearby? \n"
			 + "Jim:	I'm sorry. I don't know.\n"
			 + "Ana:	Well, thanks anyway. \n"
			 + "Jim:	So, you just moved here?\n"
			 + "Ana:	That's right, from the east coast.\n"
			 + "Jim:	Oh really? I came here from Chicago ten years ago. How do you like the west coast so far?\n"
			 + "Ana:	A lot. I always wanted to live in Portland. So I took a chance and here I am.\n"
			 + "Jim:	Yes. It's beautiful here. Well listen, if there's anything I can do for you, just call.\n"
			 + "Ana:	OK, thanks!	\n",

			"Looking for a job\n"
			 + "Director:	Please take a seat. We received your resume last week. Your credentials are excellent. 	\n"
			 + "Susan:	Thank you. 	\n"
			 + "Director:	After you finished school you went to work for an insurance company. What were your duties there?\n"
			 + "Susan:	At first I assisted the vice president of corporate sales. I did most of his legwork for him and took care of all the administrative duties. \n"
			 + "Director:	I see you were promoted twice. \n"
			 + "Susan:	Yes, currently I'm the regional sales representative.\n"
			 + "Director:	May I ask why you want to leave your present employer after all this time?\n"
			 + "Susan:	 	The position you advertised offers me the opportunity to move into a managerial position. I believe this is the right step at this point in my career. \n"
			 + "Director:	I see. You're a very interesting candidate. I have to discuss your application with my colleagues. We'll get back to you next week.  \n"
			 + "Susan:	Thank you very much.  \n"
			 + "Director:	You're welcome.\n",

			"The holiday season\n"
			 + "Ingrid:	I just finished sending all my Christmas cards. And except for the sweater I want to give my husband, I even have all my gifts. \n"
			 + "Bob:	Congratulations. This will be a very lonely holiday season for me.\n"
			 + "Ingrid:	I thought your brother and his wife were coming to visit you for Hanukkah.\n"
			 + "Bob:	No, I just spoke to them. They're just too busy to travel this year.\n"
			 + "Ingrid:	Well, if you want to celebrate Christmas with us...\n"
			 + "Bob:	Are you doing the whole spiel?\n"
			 + "Ingrid:	Of course. Without a Christmas tree, Christmas carols, cookies, and presents under the tree, Christmas just isn't the same for me.\n"
			 + "Bob:	But I don't have any presents to give you.\n"
			 + "Ingrid:	Well, you still have time to shop until the twenty fifth. I'm just kidding. Presents or no presents, we'd love to have you. \n"
			 + "Bob:	OK. Let's do it. You can count me in.\n",

			"Traveling\n"
			 + "Jane:	Hi, Monica, how are you?\n"
			 + "Monica:	I'm OK. I'm very busy at work these days.\n"
			 + "Jane:	Me too. I need a break. I can't wait for my next vacation.\n"
			 + "Monica:	I have a week off next month. My husband and I are going to the Caribbean for seven days.\n"
			 + "Jane:	That sounds exciting! I heard they have beautiful beaches over there. Where exactly are you planning to go?\n"
			 + "Monica:	First, we'll fly to Puerto Rico. Then, we'll go to Barbados, Aruba, and Jamaica. We're also going to take the boat between the islands.\n"
			 + "Jane:	But you won't have time to relax with that itinerary.\n"
			 + "Monica:	Maybe not, but it's going to be an adventure.\n"
			 + "Jane:	Listen, I have to go now. Have a great time!\n"
			 + "Monica:	OK. I'll send you a postcard.\n",

			"Hobbies\n"
			 + "Louise:	Hello, neighbor. Long time no see. You look great.\n"
			 + "John:	Well, I started exercising three times a week.\n"
			 + "Louise:	Good decision. I should take up regular exercise as well.\n"
			 + "John:	But you do all this gardening. With a lot of success, by the way. Your roses are beautiful this year. \n"
			 + "Louise:	Thanks. I enjoy working in the garden so much, it doesn't even feel like exercise. \n"
			 + "John:	How's your husband?  \n"
			 + "Louise:	Fine. He started redoing the rec-room this weekend. I hope all the hammering didn't bother you.\n"
			 + "John:	Oh, not at all. Peter and I went hiking. We weren't even around to feel disturbed.\n"
			 + "Louise:	Lucky you. It sure bothered me. I couldn't get any reading done.\n"
			 + "John:	Still into reading mysteries?\n"
			 + "Louise:	You bet.\n"
			 + "John:	Well, don't let the bad guys get away!\n"
			 + "Louise:	I won't. See you around.\n"
			 + "John:	Bye!\n",

			"American culture and television\n"
			 + "Fred:	Hi, how was your weekend?\n"
			 + "John:	I planned to go to Vermont, but because of the weather, we decided to stay home.\n"
			 + "Mary:	Yes, the snow kept me home, too. I watched TV all weekend.\n"
			 + "John:	Did you have a chance to watch the documentary about the Amazon jungle? \n"
			 + "Mary:	No, my husband didn't want to. I was really disappointed. We ended up watching a movie instead. \n"
			 + "Fred:	Which movie did you see?\n"
			 + "Mary:	A rerun of a Hitchcock movie.\n"
			 + "Fred:	I love Hitchcock. I can't get enough of his movies. Isn't Psycho great?\n"
			 + "John:	You can't convince me to watch a horror movie. I prefer to watch a sitcom or even a soap opera. Besides, I'd rather read.\n"
			 + "Fred:	I hate to break this up, but we have to get back to work.\n"
			 + "John:	If duty calls...\n",

			"U.S. Federal agencies\n"
			 + "Clerk:	Next!\n"
			 + "Evelyn:	Good morning. I need five airmail stamps, please.\n"
			 + "Clerk:	Sure. Anything else?\n"
			 + "Evelyn:	Yes. I also want a money order for two hundred dollars.\n"
			 + "Clerk:	OK. Please fill out these three forms and sign here. \n"
			 + "Evelyn:	Fine.\n"
			 + "Clerk:	You are sending the money order within the United States, aren't you?\n"
			 + "Evelyn:	No, it's going to Argentina. \n"
			 + "Clerk:	In that case, you need to fill out this form as well.\n"
			 + "Evelyn:	Another form?\n"
			 + "Clerk:	Yes, sorry. Can I help you with anything else?\n"
			 + "Evelyn:	Yes, you have passport applications, don't you?\n"
			 + "Clerk:	Well, for that you'll have to go stand in that line over there.\n"
			 + "Evelyn:	You're kidding, aren't you?\n"
			 + "Clerk:	No, unfortunately I'm not.\n"
			 + "Evelyn:	How frustrating!\n"
			 + "Clerk:	I know it is. Sorry about that.\n",

			"Education\n"
			 + "Principal:	You just moved here two weeks ago?\n"
			 + "Mother:	Yes, we're still trying to adjust to our new home.\n"
			 + "Principal:	We will do what we can to help your son make the transition to his new school. I see he finished fifth grade as an honor student.\n"
			 + "Mother:	Yes, we're very proud of him. We're just worried that the curriculum is so different here that he will have trouble catching up. Can you recommend a tutor?\n"
			 + "Principal:	Sure.\n"
			 + "Mother:	We want to help him ourselves, but both my husband and I are working...\n"
			 + "Principal:	Don't worry, your son may not have any trouble catching up by himself. And if necessary, we will set him up with a tutor. I myself will act as his advisor and watch his progress closely. Let's talk to each other after the first week of classes.\n"
			 + "Mother:	Thanks. \n",

			"Ceremonies\n"
			 + "Elsa:	The bride looked beautiful, didn't she?\n"
			 + "Linda:	Yes, and so did the groom. He's so handsome.\n"
			 + "Peter:	You think so?\n"
			 + "Linda:	Yes, I do.	\n"
			 + "Peter:	Hmm.\n"
			 + "Linda:	Jealous?\n"
			 + "Peter:	No, I have no reason to be. Soon we'll get married ourselves. I'll look very handsome and you'll be a lovely bride.\n"
			 + "Elsa:	Oh, yes. Have you decided on a date for your wedding?\n"
			 + "Linda:	May twenty fifth.\n"
			 + "Elsa:	What's the matter, Peter? You're suddenly pale.\n"
			 + "Peter:	May twenty fifth. That's... so soon.\n"
			 + "Linda:	Hey, are you getting cold feet?\n"
			 + "Peter:	No, I just didn't realize it would be so soon.\n"
			 + "Linda:	Neither did I.\n"
			 + "Rick:	Hello. This is a joyous occasion. Don't be so serious.\n"
			 + "Elsa:	Linda and Peter are getting the jitters about their upcoming wedding.\n"
			 + "Rick:	Well, so did we before ours.\n"
			 + "Elsa:	Oh, did we?\n"
			 + "Rick:	Yes. But I'm glad I didn't change my mind.\n",

			"Renting a car\n"
			 + "Mark:	Hello. I would like to rent a car for two days.\n"
			 + "Agent:	OK. What kind of car did you have in mind?\n"
			 + "Mark:	The smallest and the cheapest one you have will do.\n"
			 + "Agent:	A sedan is the least expensive car we have. We have one that is very economical.\n"
			 + "Mark:	Sounds good.\n"
			 + "Agent:	May I see your driver's license, please?\n"
			 + "Mark:	Sure, here you go. \n"
			 + "Agent:	Thanks. Please fill out this form. Write your address, and sign your name at the bottom of the page. The price includes unlimited mileage and the mandatory collision insurance.\n"
			 + "Mark:	Oh, great! That's better than I thought.\n"
			 + "Agent:	Here are your keys.\n"
			 + "Mark:	Do I have to return the car to this location?\n"
			 + "Agent:	No, you can drop it off at any of our local branches.\n"
			 + "Mark:	Thanks.\n"
			 + "Agent:	You're welcome. Drive safely and buckle up!\n",

			"Urban life\n"
			 + "Roger:	Carol, this is my sister Linda.\n"
			 + "Carol:	Nice to meet you. Roger talks about you all the time.\n"
			 + "Linda:	He does?\n"
			 + "Roger:	Don't worry. I didn't ruin your reputation.\n"
			 + "Carol:	I understand you live on Electric Avenue.\n"
			 + "Linda:	Yes, that's right.\n"
			 + "Carol:	I used to live there five years ago. I loved going to Sullivan Park. In the summer, people would have picnics there.\n"
			 + "Linda:	Not anymore. Unfortunately, the area is becoming more and more dangerous. \n"
			 + "Carol:	Really?\n"
			 + "Linda:	Yes, there's a lot of crime now:	carjackings, muggings, you name it. Even gangs are moving in.\n"
			 + "Carol:	That's too bad. When I was living there, it was a really nice neighborhood.\n"
			 + "Linda:	Just last week when I was jogging someone broke into my apartment.\n"
			 + "Carol:	Did they take anything?\n"
			 + "Linda:	No, they were probably scared away by a neighbor.\n"
			 + "Carol:	Are you planning to move?\n"
			 + "Linda:	Actually, I was thinking about it.\n",

			"Traffic\n"
			 + "John:	I hate driving during rush hour.\n"
			 + "Sharon:	I know, but we have to be at work at nine o'clock sharp.\n"
			 + "John:	And so do a lot of other people. This traffic is bumper to bumper. We're going to be late.\n"
			 + "Sharon:	Look, there's an accident ahead. How about getting off the freeway?\n"
			 + "John:	Good idea. There might be less traffic on the streets.\n"
			 + "Sharon:	Watch out! You just cut off the car behind you, and you didn't even use your blinker. \n"
			 + "John:	Sorry. I usually don't drive as recklessly as I am today. \n"
			 + "Sharon:	I hope not.\n"
			 + "John:	I'm sure we'll go a little faster on the streets. But let me tell you, tomorrow I'll take the train.  \n"
			 + "Sharon:	Me too. How about some music?\n"
			 + "John:	Sure. I brought more tapes today. They're in the glove compartment.\n",

			"In the hotel\n"
			 + "David:	This is room two-O-nine.\n"
			 + "Manager:	Yes, how may I help you, sir?\n"
			 + "David:	I would like another room.\n"
			 + "Manager:	Is there a problem?\n"
			 + "David:	Well, the shower in my room doesn't work.\n"
			 + "Manager:	I'm sorry. I don't have any other rooms available at the moment. But I will send someone to take a look at your shower.\n"
			 + "David:	How soon will that be? \n"
			 + "Manager:	It might be about an hour. \n"
			 + "David:	That's unacceptable. I have an appointment in an hour, and I need to take a shower first.\n"
			 + "Manager:	I'm sorry, sir. If I could, I would help you. \n"
			 + "David:	So, what do you suggest I do?\n"
			 + "Manager:	Well, in the meantime, you could enjoy the complimentary breakfast that we'll send to your room.\n"
			 + "David:	This will hardly take care of the problem, but thanks. And make sure my shower is fixed as soon as possible.\n"
			 + "Manager:	Of course. I'll continue to look for another room for you as well. And sorry for the inconvenience.\n",

			"Getting things fixed\n"
			 + "Tenant:	Hi, Mrs. Rogers. This is Steve, your tenant in apartment thirteen.\n"
			 + "Mrs. Rogers:	Hi, Steve. I haven't seen you for a long time.\n"
			 + "Tenant:	Well, I've been busy.\n"
			 + "Mrs. Rogers:	What can I do for you?\n"
			 + "Tenant:	There are some problems in the apartment. The faucet in the kitchen is leaking.\n"
			 + "Mrs. Rogers:	OK. I'll send the plumber tomorrow to take a look at it. Anything else?\n"
			 + "Tenant:	Yes. The heater isn't working well. \n"
			 + "Mrs. Rogers:	They still haven't fixed it? I sent someone to look at it last week. \n"
			 + "Tenant:	I know.\n"
			 + "Mrs. Rogers:	What's wrong with it now?\n"
			 + "Tenant:	Well, it makes a lot of noise, and we only get a little heat.\n"
			 + "Mrs. Rogers:	They should have fixed it the first time. I'll call them again.\n"
			 + "Tenant:	Perfect. I'll be here.\n",

			"Settling down\n"
			 + "Tony:	Hey, everybody! I'd like to propose a toast to our friend Jerry! He's getting married tomorrow, and I wanna wish him all the best.\n"
			 + "Jerry:	Thanks, guys. I can't believe this is finally happening. I have a great job and soon I'll have an amazing wife. And we've recently bought a house. I think I've just fulfilled my dreams. \n"
			 + "Tony:	Well, let's hope you don't have a rude awakening.\n"
			 + "Jerry:	You're all just jealous.\n"
			 + "Tony:	Well, you're right and we're all happy for you, buddy. Actually, I have something to confess.\n"
			 + "Jerry:	What's the matter?\n"
			 + "Tony:	Well, I proposed to Gina. \n"
			 + "Jerry:	And? \n"
			 + "Tony:	We got engaged yesterday.\n"
			 + "Jerry:	Congratulations! Cheers!\n",

			"Thirty\n"
			 + "Jill:	Wow! That lasagna was delicious. \n"
			 + "Ken:	Thank you. Does anybody want dessert? \n"
			 + "Sandy:	Yeah, ice cream sounds good to me.\n"
			 + "Jill:	No, thanks. I've been gaining too much weight lately.\n"
			 + "Sandy:	Oh, now you're making me feel guilty. \n"
			 + "Ken:	OK. Who's going to wash the dishes?\n"
			 + "Jill:	Not me. I've been cleaning the bathroom every weekend. I even scrubbed the bathtub really well. \n"
			 + "Sandy:	It's not my turn. I've been dusting the furniture for the last three months. Besides, I vacuumed yesterday. \n"
			 + "Ken:	Well, I just cooked dinner. I'm not going to do the dishes also.\n"
			 + "Jill:	OK, OK. Sandy and I will do them together.\n"
			 + "Sandy:	Fine. You wash and I'll dry.\n",

			"Summer in the USA\n"
			 + "David:	John, Mary, you made it. Better late than never. \n"
			 + "John:	Well, the directions you gave me were very confusing.\n"
			 + "David:	I apologize.  Come on, taste the hors d'oeuvres over here.\n"
			 + "Mary:	Mmm, they're delicious. The person who made them must be a professional.\n"
			 + "David:	My wife Jessica prepared them.\n"
			 + "John:	Where is she, anyway?\n"
			 + "David:	She went to pick up Tommy from summer camp.\n"
			 + "John:	Hey, is it the same one that we went to?\n"
			 + "David:	Yes. Remember our swimming coach?\n"
			 + "John:	Of course. He's the one who taught me how to swim. Have you seen him lately?\n"
			 + "David:	He's the director now.\n"
			 + "John:	Wow. He's moving up in the world.\n"
			 + "Mary:	Is he the one whose son won the swimming competition last year?\n"
			 + "John:	Yeah, that's him.\n"
			 + "David:	OK. The food is ready. Here are the delicious ribs that I promised you.\n"
			 + "Mary:	I'm so hungry.\n",

			"Politics and Democracy\n"
			 + "Bob:	Have you been following the presidential campaign this year?\n"
			 + "Chris:	More or less. I watched the debate last night.\n"
			 + "Martha:	Me too. I like the Republican candidate.\n"
			 + "Bob:	Really, he's too conservative for me. I know he has gone up in the polls lately, but I think he lost the debate last night.\n"
			 + "Chris:	I don't think so. As usual, he showed that he's well informed and that he's a terrific speaker.\n"
			 + "Martha:	Besides, he has a lot of experience in Washington, D.C. where he's very well respected.  He's a former senator.\n"
			 + "Bob:	Well, I think that the Democrats have a better platform.\n"
			 + "Chris:	I haven't made up my mind yet. I still don't know who to vote for.\n",

			"Traveling abroad\n"
			 + "John:	Hi. I was supposed to pick up my tickets today.\n"
			 + "Agent:	Yes. I remember. Please take a seat.\n"
			 + "John:	Were you able to get me a discount after all?\n"
			 + "Agent:	Yes. I got ten percent off for you.	 \n"
			 + "John:	That's good news.\n"
			 + "Agent:	OK. Here are your cruise vouchers, your plane tickets, and a complete itinerary.\n"
			 + "John:	Is that everything?\n"
			 + "Agent:	Well, you know you have to get a passport, right?\n"
			 + "John:	Yes. I went to the post office,	but it was closed.\n"
			 + "Agent:	Well, you really ought to go to the Federal building directly. It'll be faster.\n"
			 + "John:	Thanks for the tip, but I'd rather wait for the post office to open. The Federal building is all the way downtown. \n"
			 + "Agent:	Yes, but you might not get it in time. Is there anything else I can do for you? \n"
			 + "John:	No, thanks.\n"
			 + "Agent:	Well, have a great trip.\n",

			"The media and communications\n"
			 + "Lisa:	Let me flip through the channels. I'm not sure what's on tonight.\n"
			 + "Chris:	Why didn't you buy the TV guide?\n"
			 + "Lisa:	When I got to the store they had already sold every single copy.\n"
			 + "Chris:	Well, I know the sports channel is going to televise the boxing match live. It'll be broadcast all over the world. \n"
			 + "Lisa:	Let's see what else is on.\n"
			 + "Chris:	Wait! Go back to the news.\n"
			 + "Lisa:	No, the news is so depressing.\n"
			 + "Chris:	What are you looking for?\n"
			 + "Lisa:	A sitcom or a movie.\n"
			 + "Chris:	Although, sitcoms are OK, I'd rather watch a sport event or music videos on MTV any day. Give me the remote control.\n"
			 + "Lisa:	No way.\n"
			 + "Chris:	Fine. While you watch TV all by yourself, I'll go read the sports section of the newspaper.	 	\n",

			"Bargaining\n"
			 + "Jessica:	Hello! Take a look around. Everything is in good condition. \n"
			 + "Peter:	How much is this reclining chair?\n"
			 + "Jessica:	It was a hundred, but I'll give it to you for eighty. \n"
			 + "Peter:	That's a bit much. Maybe I'll come back this afternoon.\n"
			 + "Jessica:	Well, a lot more people will be stopping by later. By this afternoon I'll probably have sold it.\n"
			 + "Peter:	What's your lowest price?\n"
			 + "Jessica:	Make me an offer.\n"
			 + "Peter:	I'll give you fifty.\n"
			 + "Jessica:	No way. I can't go lower then seventy-five\n"
			 + "Peter:	How about sixty-five?\n"
			 + "Jessica:	Fine. You've got yourself a deal. And come back soon. We'll be selling stuff every weekend.\n"
			 + "Peter:	Yes, maybe I will.\n",

			"Cultural Events\n"
			 + "Claudia:	Hi, Sandy. How was your thanksgiving?\n"
			 + "Sandy:	Wonderful. We all went to my parents' new house.\n"
			 + "Claudia:	Is that the one near the freeway that was built last year?\n"
			 + "Sandy:	Yes! Anyway, the turkey was all ready when I got there. But my favorite part is always the stuffing and the mashed potatoes. The pumpkin pie was also fantastic, naturally, since it was made by yours truly. We really pigged out.\n"
			 + "Claudia:	Who else was there? \n"
			 + "Sandy:	My brother Tony. He and his friends were watching the football game.\n"
			 + "Claudia:	Did he finally get his hair cut?\n"
			 + "Sandy:	Yes. I was surprised.\n"
			 + "Claudia:	Well, I went out to eat with my daughter. My oven wasn't working.\n"
			 + "Sandy:	That's too bad.\n"
			 + "Claudia:	Actually, it was quite nice. At least I didn't have to do all the cooking.\n"
			 + "Sandy:	Tell me, did you get your oven fixed?\n"
			 + "Claudia:	No, not yet. It'll be repaired next week.\n",

			"Services\n"
			 + "Mechanic:	Good morning! What seems to be the problem?\n"
			 + "Emily:	Well, my car stopped all of a sudden, and I couldn't get it started again. So, I had it towed here.\n"
			 + "Mechanic:	If you leave it here, I'll try to check it later.\n"
			 + "Emily:	Is there any way you could work on it right away? I'm late for work as it is.\n"
			 + "Mechanic:	Well, if you give me a minute, I'll see what I can do.\n"
			 + "Emily:	Thanks so much.\n"
			 + "Mechanic:	I jump started your car and it's running fine. But you'll need a new battery soon.\n"
			 + "Emily:	Not today. I need to get to work.\n"
			 + "Mechanic:	Suit yourself. But if you don't get a battery soon, you'll have the same problem again.\n",

			"Music\n"
			 + "Cindy:	What a great band!\n"
			 + "Edward:	Yes. The drummer was great.\n"
			 + "Cindy:	I thought the saxophone player was outstanding.\n"
			 + "Edward:	You know, I could've been a great musician myself if I had pursued it more seriously. \n"
			 + "Peter:	Really? What instrument did you play?\n"
			 + "Edward:	The piano. I was really into rock and roll.\n"
			 + "Peter:	So, how come you never pursued a career in music?\n"
			 + "Edward:	Well. I was afraid the work wouldn't be steady enough.\n"
			 + "Cindy:	What about now?\n"
			 + "Edward:	If I had more time I would pursue it as a hobby.\n"
			 + "Peter:	I think you should.\n"
			 + "Edward:	I would've liked to have been able to keep up with it.\n"
			 + "Peter:	I know what you mean. I wish I had continued playing too.\n"
			 + "Edward:	There's always tomorrow.\n",

			"Cultural diversity in the USA\n"
			 + "Beth:	Shannon told me you're sending Jessica to an after-school Chinese language program.\n"
			 + "Wayne:	Yes, we want to make sure that she has a chance to use Chinese on a daily basis.\n"
			 + "Beth:	I think it's great that you're doing this. There are several languages in my background, but none of them were passed on to me. \n"
			 + "Wayne:	Really? What languages?\n"
			 + "Beth:	Well, my mother's parents were English and German and I think my father's parents were from Mexico.\n"
			 + "Wayne:	You're not sure?\n"
			 + "Beth:	No! I asked my dad where his family came from and he said he didn't really know. In fact, I'm not even sure what his last name used to be before his family changed it. I know his father spoke Spanish but he wouldn't teach it to his kids because it might inhibit their English. \n"
			 + "Wayne:	What a shame!\n"
			 + "Beth:	I think so, too. I wish I had learned another language as a child. It's more difficult as an adult.\n",

			"The Hollywood craze\n"
			 + "Emily:	Did you hear the latest scandal about Elizabeth Taylor?	\n"
			 + "Karen:	No, what is it?\n"
			 + "Emily:	There's a rumor that she's actually married to two people.\n"
			 + "Frank:	Give me a break! Where do you get these things?\n"
			 + "Emily:	From the tabloids. I read it yesterday, when I was in line at the market.\n"
			 + "Frank:	If I were you, I wouldn't believe that sensationalist trash. Those magazines are not exactly the most reliable source.\n"
			 + "Karen:	Have you seen the previews for her new movie?\n"
			 + "Frank:	Yes. It's nothing to write home about.\n"
			 + "Emily:	But the critics said that it was a real tearjerker.\n"
			 + "Karen:	Well, the movie's coming out next week. I suggest we go see it and judge for ourselves. \n"
			 + "Emily:	Maybe. I'll get back to you."
		};

	public static String getLessonText(int lessonNumber) {				
		return data[lessonNumber];
	}
	
	public static int getNumberOfLessons() {				
		return data.length;
	}

}
